alias ls='ls --color=auto'
alias pygrep='grep --include=*.py'
alias opa='cd /usr/local/opa/'
alias twh='touch /usr/local/opa/opa_engine/apache_django.wsgi'
alias gs='git status'
alias dbserver='ssh ubuntu@54.212.250.134 -A'
